package video.minevideo;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.screen.GameMenuScreen;
import net.minecraft.client.gui.screen.TitleScreen;
import net.minecraft.client.gui.screen.multiplayer.ConnectScreen;
import net.minecraft.client.network.ServerAddress;
import net.minecraft.client.network.ServerInfo;
import net.minecraft.client.option.Perspective;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.util.concurrent.Executors;

/** Small glue only: actual game rendering, accounts, networking and capture remain upstream. */
public final class CaptureGuard implements ClientModInitializer {
    private static final Logger LOG = LoggerFactory.getLogger("minevideo-capture");
    private static final Gson GSON = new Gson();
    private static volatile JsonObject snapshot = new JsonObject();
    private static volatile long lastRenderNanos = 0;
    private static Config config;

    private record Config(String token, int port, String player, String serverAddress) {}

    @Override
    public void onInitializeClient() {
        var path = FabricLoader.getInstance().getConfigDir().resolve("minevideo-capture.json");
        if (!Files.isRegularFile(path)) {
            LOG.warn("Capture guard disabled: import a client pack generated by mine-video client-pack");
            return;
        }
        try {
            var value = GSON.fromJson(Files.readString(path), Config.class);
            if (value.token() == null || value.token().length() < 24 || value.port() < 1024
                    || value.port() > 65535 || value.player() == null
                    || !value.player().matches("[A-Za-z0-9_]{3,16}")
                    || value.serverAddress() == null || value.serverAddress().isBlank()) {
                throw new IllegalArgumentException("Invalid capture guard configuration");
            }
            HttpServer server = HttpServer.create(new InetSocketAddress("127.0.0.1", value.port()), 8);
            config = value;
            server.createContext("/health", this::health);
            server.createContext("/connect", this::connect);
            server.createContext("/quit", this::quit);
            server.setExecutor(Executors.newFixedThreadPool(2, runnable -> {
                Thread thread = new Thread(runnable, "minevideo-guard-http");
                thread.setDaemon(true);
                return thread;
            }));
            Thread starter = new Thread(server::start, "minevideo-guard-start");
            starter.setDaemon(true);
            starter.start();
            Runtime.getRuntime().addShutdownHook(new Thread(() -> server.stop(0)));
            LOG.info("Capture guard listening on loopback port {}", value.port());
        } catch (Exception error) {
            config = null;
            LOG.error("Capture guard could not start: {}", error.getClass().getSimpleName());
        }
    }

    private boolean authorize(HttpExchange exchange, String method) throws IOException {
        var provided = exchange.getRequestHeaders().getFirst("Authorization");
        if (config == null || provided == null || !MessageDigest.isEqual(
                provided.getBytes(StandardCharsets.UTF_8),
                ("Bearer " + config.token()).getBytes(StandardCharsets.UTF_8))) {
            respond(exchange, 401, "{\"error\":\"unauthorized\"}");
            return false;
        }
        if (!exchange.getRequestMethod().equals(method)) {
            respond(exchange, 405, "{\"error\":\"method not allowed\"}");
            return false;
        }
        return true;
    }

    private static void respond(HttpExchange exchange, int code, String body) throws IOException {
        byte[] bytes = body.getBytes(StandardCharsets.UTF_8);
        exchange.getResponseHeaders().set("Content-Type", "application/json; charset=utf-8");
        exchange.getResponseHeaders().set("Cache-Control", "no-store");
        exchange.sendResponseHeaders(code, bytes.length);
        try (var stream = exchange.getResponseBody()) { stream.write(bytes); }
        exchange.close();
    }

    private void health(HttpExchange exchange) throws IOException {
        if (!authorize(exchange, "GET")) return;
        var response = snapshot.deepCopy();
        response.addProperty("protocol", 1);
        response.addProperty("renderAgeMs", lastRenderNanos == 0 ? Long.MAX_VALUE
                : (System.nanoTime() - lastRenderNanos) / 1_000_000);
        respond(exchange, 200, GSON.toJson(response));
    }

    private void connect(HttpExchange exchange) throws IOException {
        if (!authorize(exchange, "POST")) return;
        var client = MinecraftClient.getInstance();
        client.execute(() -> {
            if (client.world == null && !(client.currentScreen instanceof ConnectScreen)) {
                ConnectScreen.connect(new TitleScreen(), client, ServerAddress.parse(config.serverAddress()),
                        new ServerInfo("MineVideo", config.serverAddress(), ServerInfo.ServerType.OTHER), false, null);
            }
        });
        respond(exchange, 202, "{\"accepted\":true}");
    }

    private void quit(HttpExchange exchange) throws IOException {
        if (!authorize(exchange, "POST")) return;
        respond(exchange, 202, "{\"accepted\":true}");
        MinecraftClient.getInstance().scheduleStop();
    }

    public static void tick() {
        if (config == null) return;
        var client = MinecraftClient.getInstance();
        var server = client.getCurrentServerEntry();
        boolean owned = client.player != null && server != null
                && config.player().equals(client.player.getGameProfile().getName())
                && config.serverAddress().equals(server.address);
        if (owned) {
            client.options.hudHidden = true;
            client.options.pauseOnLostFocus = false;
            client.options.setPerspective(Perspective.FIRST_PERSON);
            client.options.getFov().setValue(70);
            if (client.currentScreen instanceof GameMenuScreen) client.setScreen(null);
        }
        var state = new JsonObject();
        state.addProperty("player", client.player == null ? "" : client.player.getGameProfile().getName());
        state.addProperty("server", server == null ? "" : server.address);
        state.addProperty("world", client.world == null ? "" : client.world.getRegistryKey().getValue().toString());
        state.addProperty("hudHidden", client.options.hudHidden);
        state.addProperty("screen", client.currentScreen == null ? null : client.currentScreen.getClass().getSimpleName());
        state.addProperty("fps", client.getCurrentFps());
        var position = new JsonArray();
        if (client.player != null) {
            position.add(client.player.getX()); position.add(client.player.getY()); position.add(client.player.getZ());
        }
        state.add("position", position);
        snapshot = state;
    }

    /** Called only after renderWorld returns; a menu frame is not a world heartbeat. */
    public static void renderedWorld() { lastRenderNanos = System.nanoTime(); }
}
